name: cloudbank-classroom-usage
channels: [conda-forge, defaults]
dependencies:
  - python>=3.10
  - pip
  - pip:
    - pandas
    - pyyaml
    - requests
    # otter_standalone_use.py reads Firestore
    - firebase-admin
